
version: 2

models:
    - name: vouchers
      description: "Vouchers model"
      columns:
          - name: voucher_code
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: status
            description: "The status of the voucher, whether redeemed or clipped"
            tests:
              - accepted_values:
                  values: ['clipped', 'redeemed'] 


    - name: master_calendar
      description: "date dimension"
      columns:
          - name: date
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
